baseURL = 'https://russellrollins.com/'
languageCode = 'en-us'
title = 'Russell Rollins'

theme = "hugo-theme-codex"

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/Russell_Rollins"
  github = "https://github.com/russellrollins"
  email = "mailto:russell@russellrollins.com"
  linkedin = "https://www.linkedin.com/in/russellrollins/"
  
  iconOrder = ["Twitter", "GitHub", "Email", "LinkedIn"]
